[package]
name = "componentize_add"
version = "0.1.0"
edition = "2021"

[dependencies]

[lib]
crate-type = ["cdylib", "rlib"]

[profile.release]
# Tell `rustc` to optimize for small code size.
# opt-level = "s"
# strip = true