[package]
name = "componentize_mrbe"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[profile.release]
codegen-units = 1
opt-level = "s"
debug = false
strip = false
lto = true

[dependencies]
mrubyedge = "1.0.0-rc2"
wit-bindgen = "0.36.0"
